spring:
  application:
    name: todoApp
  datasource:
    url: jdbc:postgresql://localhost:5432/todos_app_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/master.xml
license:
  key:
    path: src/main/resources/.application_secret.txt
  validation:
    url: http://localhost:8010

